export const formStyles = {
  container: 'bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 shadow-lg p-8',
  form: 'space-y-8',
  fieldGroup: 'space-y-3',
  label: 'block text-sm font-medium text-gray-700 dark:text-white/90',
  input: 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-brand-500 focus:ring-brand-500 dark:bg-white/[0.03] dark:border-gray-800 dark:text-white/90 transition-all duration-200',
  select: 'mt-1 block w-full rounded-lg border-gray-300 shadow-sm focus:border-brand-500 focus:ring-brand-500 dark:bg-white/[0.03] dark:border-gray-800 dark:text-white/90 transition-all duration-200',
  checkbox: 'rounded border-gray-300 text-brand-500 shadow-sm focus:border-brand-500 focus:ring-brand-500 dark:bg-white/[0.03] dark:border-gray-800 dark:text-brand-600 transition-all duration-200',
  button: 'w-full rounded-lg bg-brand-500 px-6 py-3 text-sm font-medium text-white shadow-sm hover:bg-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 dark:bg-brand-600 dark:hover:bg-brand-700 transition-all duration-200',
  error: 'text-red-500 text-sm mt-2',
  helperText: 'text-gray-500 text-sm mt-2 dark:text-white/70',
  formHeader: 'text-2xl font-semibold text-gray-900 dark:text-white mb-8',
  formDescription: 'text-gray-600 dark:text-white/70 mb-6',
  grid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
  gridItem: 'space-y-3',
  statusBadge: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
  statusBadgePending: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
  statusBadgeInactive: 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200',
  passwordStrength: 'flex items-center justify-between mt-2',
  passwordMeter: 'w-full bg-gray-200 rounded-full h-1.5 dark:bg-gray-800',
  passwordMeterBar: 'bg-brand-500 h-1.5 rounded-full transition-all duration-300',
  passwordStrengthText: 'text-xs text-gray-500 dark:text-white/70',
  passwordRequirements: 'mt-2 text-xs text-gray-500 dark:text-white/70 space-y-1',
  passwordRequirement: 'flex items-center',
  passwordRequirementIcon: 'w-3 h-3 rounded-full mr-2',
  passwordRequirementValid: 'bg-green-500',
  passwordRequirementInvalid: 'bg-gray-400',
  showPassword: 'text-sm text-gray-500 dark:text-white/70 hover:text-gray-700 dark:hover:text-white cursor-pointer',
};
